num_train_steps: 1e7
num_train_iters: 1
num_seed_steps: 1000
device: cuda:0
seed: 1
n_params: ???

log_frequency_step: 10
log_save_tb: true
save_video: true
eval_frequency_step: 50
num_eval_episodes: 32

# global params
lr: 2.5e-4
batch_size: 8

env:
  env_id: Mazelab12-v1
#  env_id: BreakoutDeterministic-v4
  num_envs: 8
  image_size: 84
  pytorch_dim_order: true
  frame_stack: 4
  device: ${device}

agent:
  name: ppo
  num_envs: ${env.num_envs}
  recurrent_policy: false
  lr: ${lr}
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.01
  num_steps: 128
  num_mini_batch: ${batch_size}
  num_env_steps: ${num_env_steps}
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.5
  clip_param: 0.2
  ppo_epoch: 4
  device: ${device}

  use_gae: false
  gae_lambda: 0.95
  use_proper_time_limits: False

# hydra configuration
hydra:
  name: ${env.env_id}
  run:
    dir: ./runs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
