num_train_steps: 1e6
num_train_iters: 1
device: cuda:0
seed: 127
num_envs: ${agent.num_envs}

log_frequency_step: 1e3
log_save_tb: true
save_video: true
eval_frequency_step: 5e4
num_eval_episodes: 30

defaults:
#  - env: atari
  - env: mazelab
#  - agent: a2c
#  - agent: a2c_rnn
  - agent: a2c_crnn
#  - agent: a2c_2am
#  - agent: ppo
#  - agent: ppo_rnn
#  - agent: ppo_crnn

# hydra configuration
hydra:
  name: ${env.env_id}
  run:
    dir: ./runs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}_${hydra.job.num}