num_train_steps: ${agent.num_env_steps}
num_train_iters: 1
num_seed_steps: 1000
device: cuda:0
seed: 1

log_frequency_step: 1e3
log_save_tb: true
save_video: true
eval_frequency_step: 5e4
num_eval_episodes: 30

defaults:
#  - env: atari
  - env: mazelab
#  - agent: a2c
#  - agent: a2c_rnn
  - agent: a2c_crnn
#  - agent: ppo
#  - agent: ppo_rnn
#  - agent: ppo_crnn

# hydra configuration
hydra:
  name: ${env.env_id}
  run:
    dir: ./runs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
