num_train_steps: ${agent.num_env_steps}
num_train_iters: 1
num_seed_steps: 1000
device: cuda:0
seed: 1
n_params: ???

log_frequency_step: 1e3
log_save_tb: true
save_video: true
eval_frequency_step: 5e4
num_eval_episodes: 10

defaults:
  - env: atari
  - agent: a2c
#  - agent: ppo

# hydra configuration
hydra:
  name: ${env.env_id}
  run:
    dir: ./runs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
