# @package _group_
env_id: CartPole-v0
env_kwargs: {}
max_timesteps: 200
obs_type: proprioceptive
image_size: 64
to_grayscale: false
episode_life: false
clip_rewards: false
cognitive_pause: 1337
frame_stack: 1
frame_skip: 1
random_initial_steps: 0
pytorch_dim_order: true
device: ${device}