# @package _group_
#  env_id: PongNoFrameskip-v4
#env_id: BreakoutNoFrameskip-v4
#env_id: MsPacmanNoFrameskip-v4
env_id: Freeway-v4
#env_id: FrostbiteNoFrameskip-v4
#  env_id: IceHockeyNoFrameskip-v4
image_size:
  - 84
  - 84
to_grayscale: true
episode_life: true
clip_rewards: true
frame_stack: 4
frame_skip: 4
random_initial_steps: 0
max_timesteps: 1000
pytorch_dim_order: true
device: ${device}
num_eval_envs: 4
num_timesteps: 20e7
reward_rescale: true
