# @package _group_
env_id: Mazelab-v0
env_kwargs:
  maze_kind: maze
  maze_size: 15
  maze_fixed: true
  goal_fixed: true
  goal_reward: true
  wall_reward: false
max_timesteps: 150
obs_type: image
image_size:
  - 64
  - 64
to_grayscale: false
episode_life: false
reward_rescale: false
clip_rewards: false
cognitive_pause: 1337
frame_stack: 1
frame_skip: 1
random_initial_steps: 0
pytorch_dim_order: true
device: ${device}
num_eval_envs: 2
num_timesteps: 5e5