env:
  env_id: Mazelab-v0
  num_envs: ${agent.num_envs}
  env_kwargs:
    maze_kind: maze
    maze_size: 11
    maze_fixed: true
    goal_fixed: false
    goal_reward: false
  image_size: 64
  to_grayscale: false
  episode_life: false
  clip_rewards: false
  augment: false
  frame_stack: 1
  frame_skip: 1
  random_initial_steps: 0
  pytorch_dim_order: true
  device: ${device}