# @package _group_
env_id: Mazelab-v0
env_kwargs:
  maze_kind: maze
  maze_size: 9
  maze_fixed: false
  goal_fixed: false
  goal_reward: false
  wall_reward: false
max_timesteps: 300
obs_type: image
image_size: 64
to_grayscale: false
episode_life: false
clip_rewards: false
mind_pause: false
frame_stack: 1
frame_skip: 1
random_initial_steps: 0
pytorch_dim_order: true
device: ${device}