# @package _group_
env_id: MiniGrid-Dynamic-Obstacles-8x8-v0
#env_id: MiniGrid-Dynamic-Obstacles-16x16-v0
#env_id: MiniGrid-Dynamic-Obstacles-Random-6x6-v0

env_kwargs: {}
obs_type: image
image_size:
  - 64
  - 64
to_grayscale: false
episode_life: false
clip_rewards: false
reward_rescale: true
cognitive_pause: 1337
frame_stack: 1
frame_skip: 1
random_initial_steps: 0
pytorch_dim_order: true
device: ${device}
num_eval_envs: 4
num_timesteps: 2e6