# @package _group_
env_id: RegularMiniPacmanNoFrameskip-v0
#env_id: AvoidMiniPacmanNoFrameskip-v0
#env_id: HunMiniPacmanNoFrameskip-v0
#env_id: AmbushMiniPacmanNoFrameskip-v0
#env_id: RushMiniPacmanNoFrameskip-v0
env_kwargs: {}
obs_type: image
image_size:
  - 64
  - 64
to_grayscale: false
episode_life: false
reward_rescale: true
clip_rewards: false
cognitive_pause: 1337
frame_stack: 1
frame_skip: 1
random_initial_steps: 0
pytorch_dim_order: true
device: ${device}