agent:
  name: a2c
  num_envs: 16
  architecture: "ff"
  recurse_depth: 0
  lr: 7e-4
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.01
  num_steps: 5
  num_env_steps: 1e7
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.5
  device: ${device}
  use_gae: false
  gae_lambda: 0.95
  use_proper_time_limits: False