# @package _group_
name: a2c
num_envs: 8
network:
  architecture: "ff"
  state_channels: 32
  hidden_size: 256
lr: 1e-3
gamma: 0.99
value_loss_coef: 0.5
entropy_coef: 0.01
num_steps: 5
eps: 1e-5
alpha: 0.99
max_grad_norm: 0.5
device: ${device}
