# @package _group_
name: a2c
num_envs: 16
num_steps: 10
device: ${device}
network_params:
  architecture: "crnn"
  state_channels: 32
  hidden_size: 256
  random_cog_fraction: 0.5
algo_params:
  lr: 7e-4
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.01
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.1
  use_timeout: true
  smooth_value_loss: true
  reward_rescale: false
  update_cognitive_values: true
  optimizer_type: rmsprop
