# @package _group_
name: a2c
num_envs: 16
num_steps: 10
device: ${device}
network_params:
  architecture: "crnn"
  state_channels: 32
  hidden_size: 256
  random_cog_fraction: 0.0
  fixed_recursive_depth: 1
  append_a_cog: true
  append_coords: true
  pool_and_inject: false
  detach_cognition: false
algo_params:
  twoAM: true
  cognitive_coef: 1.0
  cognitive_cost: 1.0
  cognitive_rewards: AD
  lr: 7e-4
  gamma: 0.99
  gamma_cog: 0.95
  value_loss_coef: 0.5
  entropy_coef: 0.01
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.1
  use_timeout: true
  smooth_value_loss: false
  reward_rescale: ${env.reward_rescale}
  update_cognitive_values: false
  optimizer_type: rmsprop
