# @package _group_
name: a2c
num_envs: 1
num_steps: 10
device: ${device}
network_params:
  architecture: "crnn"
  state_channels: 32
  hidden_size: 64
  random_cog_fraction: 0.
  fixed_recursive_depth: 1
  append_a_cog: false
  append_coords: false
  pool_and_inject: false
algo_params:
  twoAM: true
  lr: 1e-3
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.01
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.2
  use_timeout: true
  smooth_value_loss: true
  reward_rescale: ${env.reward_rescale}
  update_cognitive_values: false
  optimizer_type: rmsprop
