agent:
  name: ppo
  num_envs: ${agent.num_mini_batch}
  recurrent_policy: true
  lr: 2e-3
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.01
  num_steps: 128
  num_mini_batch: 4
  num_env_steps: 1e7
  eps: 1e-5
  alpha: 0.99
  max_grad_norm: 0.5
  clip_param: 0.2
  ppo_epoch: 4
  device: ${device}
  use_gae: false
  gae_lambda: 0.95
  use_proper_time_limits: False